### PR TITLE
return greetings message if database is empty

### PR DESCRIPTION
**Pull request by ViktorGetty**

### CODE REVIEW

**Comment by garciagregg** [comment]
Is this how we want this to work?

**Comment by ViktorGetty** [comment]
We can do any other message too. Please let me know how you/David envision this.

**Comment by garciagregg** [comment]
Can we just have zeros for everything?

**Comment by ViktorGetty** [comment]
But what would be 'everything'? If we don't even have a single entity?

**Comment by garciagregg** [comment]
Stats and Entities (0)

**Comment by ViktorGetty** [comment]
OK

**Pull request closed without merging**
